project:
  type: book

book:
  title: "MATH7432 - Computing and Algorithms for Statistics Notes"
  author: "Norah Jones"
  date: "06/08/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



